### ISSUE TITLE
Possible documentation typo?

### ISSUE THREAD

**Issue by hunterdrayman** [fire1ce/UDMP-Persistence-SSH-Keys#2]
Thanks for this useful code. Much appreciated.

I just successfully installed on my UDM-Pro but discovered I needed to use sh rather than bash on my machine. i.e.

`curl https://raw.githubusercontent.com/fire1ce/UDMP-Persistence-SSH-Keys/main/install.sh | sh`

instead of 

`curl https://raw.githubusercontent.com/fire1ce/UDMP-Persistence-SSH-Keys/main/install.sh | bash`

**Comment by fire1ce** [comment]
would you mind runing 
# which bash
on your udm pro. 
mine has bash outof the box.

**Comment by hunterdrayman** [comment]
Hi,

I did that at the time (and also searched through $PATH) and there was no
bash to be found. However, I subsequently installed wireguard as
described here:

https://github.com/tusc/wireguard-kmod#install

and noted that this project installed a few extras, including bash. Had I
done these two things in reverse order bash would have already been
present. To answer your question, though:

# which bash
/bin/bash
# ls -al /bin/bash
lrwxrwxrwx    1 root     root            32 Apr 23 08:43 /bin/bash ->
/mnt/data/wireguard/usr/bin/bash

**Comment by fire1ce** [comment]
@hunterdrayman 
thanks for the info. Had wireguard installed before i made this script. 
ill change the install to `sh`
